micronaut:
  application:
    name: todo-server

datasources:
  default:
    url: 'jdbc:h2:./database/h2db'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''

flyway:
  datasources:
    default:
      locations: classpath:db/migration
