CREATE TABLE TASK (
  ID VARCHAR(32) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  STATE VARCHAR(16) NOT NULL,
  DESCRIPTION VARCHAR(1024),
  CREATED_TIMESTAMP BIGINT NOT NULL,
  LAST_UPDATED_TIMESTAMP BIGINT NOT NULL,
  PRIORITY INTEGER,
  DEADLINE VARCHAR(10),
  PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX TASK_ID
 ON TASK(ID);

CREATE INDEX TASK_CREATED_TIMESTAMP
 ON TASK(CREATED_TIMESTAMP);

CREATE INDEX TASK_LAST_UPDATED_TIMESTAMP
 ON TASK(LAST_UPDATED_TIMESTAMP);

CREATE INDEX TASK_PRIORITY
 ON TASK(PRIORITY);

CREATE INDEX TASK_DEADLINE
 ON TASK(DEADLINE);

CREATE SEQUENCE TASK_ID_SEQUENCE
  INCREMENT BY 1
  MAXVALUE 99999999
  START WITH 1
  NO CYCLE
;
