CREATE TABLE TASK (
  ID VARCHAR(64),
  NAME VARCHAR(64),
  DESCRIPTION VARCHAR(1024),
  CREATED_TIMESTAMP BIGINT,
  LAST_UPDATED_TIMESTAMP BIGINT,
  PRIORITY INTEGER,
  DEADLINE VARCHAR(8)
);

CREATE UNIQUE INDEX TASK_ID
 ON TASK(ID);

CREATE INDEX TASK_CREATED_TIMESTAMP
 ON TASK(CREATED_TIMESTAMP);

CREATE INDEX TASK_LAST_UPDATED_TIMESTAMP
 ON TASK(LAST_UPDATED_TIMESTAMP);

CREATE INDEX TASK_PRIORITY
 ON TASK(PRIORITY);

CREATE INDEX TASK_DEADLINE
 ON TASK(DEADLINE);
