CREATE TABLE TASK (
  ID IDENTITY NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(1024),
  CREATED_TIMESTAMP BIGINT NOT NULL,
  LAST_UPDATED_TIMESTAMP BIGINT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  DEADLINE VARCHAR(10)
);

CREATE UNIQUE INDEX TASK_ID
 ON TASK(ID);

CREATE INDEX TASK_CREATED_TIMESTAMP
 ON TASK(CREATED_TIMESTAMP);

CREATE INDEX TASK_LAST_UPDATED_TIMESTAMP
 ON TASK(LAST_UPDATED_TIMESTAMP);

CREATE INDEX TASK_PRIORITY
 ON TASK(PRIORITY);

CREATE INDEX TASK_DEADLINE
 ON TASK(DEADLINE);
